index : main.o dec2bin.o dec2bin_n.o switch_choice.o prog1.o bit_swap.o prog2.o bit_swap_diff.o prog3.o bit_copy.o prog4.o even_bit_toggle.o odd_bit_toggle.o prog5.o prog6.o left_rotate_bits.o left_rotate_n_bits.o right_rotate_bits.o right_rotate_n_bits.o prog7.o count_bit_set.o count_bit_clear.o prog8.o cnt_leading_cleared_bits.o cnt_leading_set_bits.o cnt_trailing_cleared_bits.o cnt_trailing_set_bits.o prog10.o setbits.o prog11.o invert.o prog12.o
	gcc --std=c11 -Wall -o root main.o dec2bin.o dec2bin_n.o switch_choice.o prog1.o bit_swap.o prog2.o bit_swap_diff.o prog3.o bit_copy.o prog4.o even_bit_toggle.o odd_bit_toggle.o prog5.o prog6.o left_rotate_bits.o left_rotate_n_bits.o right_rotate_bits.o right_rotate_n_bits.o prog7.o count_bit_set.o count_bit_clear.o prog8.o cnt_leading_cleared_bits.o cnt_leading_set_bits.o cnt_trailing_cleared_bits.o cnt_trailing_set_bits.o prog10.o setbits.o prog11.o invert.o prog12.o

make.o : make.c 
	gcc -c make.c



dec2bin.o :  common/dec2bin.c
	gcc -c common/dec2bin.c

dec2bin_n.o :  common/dec2bin_n.c
	gcc -c common/dec2bin_n.c

switch_choice.o : common/switch_choice.c
	gcc -c common/switch_choice.c



prog1.o : prog1/prog1.c
	gcc -c prog1/prog1.c

bit_swap.o : prog1/bit_swap.c
	gcc -c prog1/bit_swap.c



prog2.o : prog2/prog2.c
	gcc -c prog2/prog2.c

bit_swap_diff.o : prog2/bit_swap_diff.c
	gcc -c prog2/bit_swap_diff.c




prog3.o : prog3/prog3.c
	gcc -c prog3/prog3.c

bit_copy.o : prog3/bit_copy.c
	gcc -c prog3/bit_copy.c





prog4.o : prog4/prog4.c
	gcc -c prog4/prog4.c

even_bit_toggle.o : prog4/even_bit_toggle.c
	gcc -c prog4/even_bit_toggle.c

odd_bit_toggle.o : prog4/odd_bit_toggle.c
	gcc -c prog4/odd_bit_toggle.c



prog5.o : prog5/prog5.c
	gcc -c prog5/prog5.c




prog6.o : prog6/prog6.c
	gcc -c prog6/prog6.c

left_rotate_bits.o : prog6/left_rotate_bits.c
	gcc -c prog6/left_rotate_bits.c

left_rotate_n_bits.o : prog6/left_rotate_n_bits.c
	gcc -c prog6/left_rotate_n_bits.c

right_rotate_bits.o : prog6/right_rotate_bits.c
	gcc -c prog6/right_rotate_bits.c

right_rotate_n_bits.o : prog6/right_rotate_n_bits.c
	gcc -c prog6/right_rotate_n_bits.c




prog7.o : prog7/prog7.c
	gcc -c prog7/prog7.c

count_bit_set.o : prog7/count_bit_set.c
	gcc -c prog7/count_bit_set.c

count_bit_clear.o : prog7/count_bit_clear.c
	gcc -c prog7/count_bit_clear.c




prog8.o : prog8/prog8.c
	gcc -c prog8/prog8.c

cnt_leading_cleared_bits.o : prog8/cnt_leading_cleared_bits.c
	gcc -c prog8/cnt_leading_cleared_bits.c

cnt_leading_set_bits.o : prog8/cnt_leading_set_bits.c
	gcc -c prog8/cnt_leading_set_bits.c

cnt_trailing_cleared_bits.o : prog8/cnt_trailing_cleared_bits.c
	gcc -c prog8/cnt_trailing_cleared_bits.c

cnt_trailing_set_bits.o : prog8/cnt_trailing_set_bits.c
	gcc -c prog8/cnt_trailing_set_bits.c


 
prog10.o : prog10/prog10.c
	gcc -c prog10/prog10.c

setbits.o : prog10/setbits.c
	gcc -c prog10/setbits.c



prog11.o : prog11/prog11.c
	gcc -c prog11/prog11.c

invert.o : prog11/invert.c
	gcc -c prog11/invert.c




prog12.o : prog12/prog12.c
	gcc -c prog12/prog12.c







